name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: "latest"
    - uses: actions/checkout@v2
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --ci --allow-privileged +all
